# Generated by Django 5.2 on 2025-04-10 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='morador_apartamento', to='apartamentos.apartamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morador_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
                'ordering': ['usuario__username'],
            },
        ),
    ]
