# Generated by Django 5.2 on 2025-04-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
