# Generated by Django 5.2 on 2025-04-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0002_initial'),
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moradores.morador')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartamentos.apartamento')),
            ],
        ),
    ]
