# Generated by Django 5.2 on 2025-04-10 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número do Apartamento')),
                ('andar', models.IntegerField(blank=True, null=True, verbose_name='Andar')),
                ('bloco', models.CharField(max_length=10, verbose_name='Bloco/Torre')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proprietario_apartamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'ordering': ['andar', 'numero'],
            },
        ),
    ]
