# Generated by Django 5.2 on 2025-04-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proprietario_apartamento', to='proprietarios.proprietario'),
        ),
    ]
