# Generated by Django 5.2 on 2025-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_initial'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número do Apartamento'),
        ),
        migrations.AddConstraint(
            model_name='apartamento',
            constraint=models.UniqueConstraint(fields=('numero', 'bloco'), name='unique_numero_bloco'),
        ),
    ]
