# Generated by Django 5.2 on 2025-04-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0003_alter_apartamento_numero_and_more'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietario_apartamento', to='proprietarios.proprietario'),
        ),
    ]
