# Generated by Django 5.2 on 2025-04-17 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0004_alter_apartamento_proprietario'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietario_apartamento', to='proprietarios.proprietario'),
        ),
    ]
