# Generated by Django 5.2 on 2025-04-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0003_alter_apartamento_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaEstacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('localizacao', models.CharField(max_length=100)),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaga_estacionamento', to='apartamentos.apartamento')),
            ],
        ),
    ]
