# Generated by Django 5.2 on 2025-04-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagaestacionamento',
            name='localizacao',
            field=models.CharField(max_length=50),
        ),
    ]
